# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-13 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(null=True)),
                ('createdby', models.TextField(null=True)),
                ('image', models.FileField(blank=True, max_length=255, null=True, upload_to='pictures/%Y/%m/%d/')),
            ],
        ),
    ]
